# This docker file uses the centos image
# VERSION 1
# Base image

FROM yaohong/centos74-ssh:v1
#FROM yaohong/python-ssh

# Maintainer
MAINTAINER linyaohong 122123498@qq.com

# Python env
RUN yum -y install python-devel  python-pip 

# Ppgrade pip
RUN pip install --upgrade pip

# docker build -t yaohong/python-ssh  .
