{
 "title": "ELK",
 "description": "CPU 内存 磁盘 IO 网络等监控指标",
 "tags": [ "ELK" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "主机名",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   },
   {
    "name": "job_name",
    "label": "job_name",
    "query": "label_values(node_exporter_build_info{env=~'$name'},job)"
   },
   {
    "name": "ELK",
    "label": "IP",
    "query": "label_values(node_exporter_build_info{job=~'ELK'},instance)"
   },
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_exporter_build_info{name=~'$name'},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "系统运行时间",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$ELK\"}"
    }
   ]
  },
  {
   "title": "CPU使用率（5m）",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$ELK\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$ELK\"} / (node_memory_MemTotal_bytes{instance=~\"$ELK\"})))* 100"
    }
   ]
  },
  {
   "title": "各分区可用空间",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {instance=~\"$ELK\",fstype=~\"ext4|xfs|ext3\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~\"$ELK\",fstype=~\"ext4|xfs|ext3\"} / node_filesystem_size_bytes{instance=~\"$ELK\",fstype=~\"ext4|xfs|ext3\"})"
    }
   ]
  },
  { "title": "Panel Title", "type": "alertlist", "gridPos": { "h": 20, "w": 3, "x": 21, "y": 0 } },
  {
   "title": "CPU 核数",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$ELK\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU iowait（5m）",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$ELK\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "当前打开的文件描述符",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$ELK\"}"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$ELK\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes{instance=~\"$ELK\"} / node_memory_MemTotal_bytes{instance=~\"$ELK\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~\"$ELK\",fstype=~\"ext4|xfs|ext3\"} / node_filesystem_size_bytes{instance=~\"$ELK\",fstype=~\"ext4|xfs|ext3\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU使用率（%）",
   "type": "graph",
   "description": "node_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的毫秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$ELK\",mode=\"system\"}[1m])) by (instance) + avg(irate(node_cpu_seconds_total{instance=~\"$ELK\",mode=\"user\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "磁盘IOwait（%）",
   "type": "graph",
   "description": "node_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的毫秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$ELK\",mode=\"iowait\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$ELK\"}",
     "legendFormat": "{{instance}}_总内存"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$ELK\"} - node_memory_MemAvailable_bytes{instance=~\"$ELK\"}",
     "legendFormat": "{{instance}}_已用"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$ELK\"}",
     "legendFormat": "{{instance}}_可用"
    }
   ]
  },
  { "title": "展开", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "磁盘每秒I/O操作（%）",
   "type": "graph",
   "description": "node_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的毫秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$ELK\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_每秒I/O操作%"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$ELK\"}",
     "legendFormat": "{{instance}}_1m"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "graph",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "iops", "label": "读取（-）/写入（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$ELK\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$ELK\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_写入"
    }
   ]
  },
  {
   "title": "磁盘读写容量大小",
   "type": "graph",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "Bps", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$ELK\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$ELK\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_写入"
    }
   ]
  },
  {
   "title": "磁盘IO读写时间",
   "type": "graph",
   "description": "Read time ms 每个磁盘分区读操作花费的秒数\n\nWrite time ms 每个磁盘分区写操作花费的秒数\n\nIO time ms 每个磁盘分区输入/输出操作花费的秒数\n\nIO time weighted 每个磁盘分区输入/输出操作花费的加权秒数",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 40 },
   "yaxes": [
    { "format": "s", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$ELK\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_读取"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$ELK\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_写入"
    }
   ]
  },
  {
   "title": "网络流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$ELK\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_in下载"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$ELK\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_out上传"
    }
   ]
  },
  {
   "title": "TCP 连接情况",
   "type": "graph",
   "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$ELK\"}",
     "legendFormat": "{{instance}}_ESTABLISHED"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~\"$ELK\"}[1m])",
     "legendFormat": "{{instance}}_ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~\"$ELK\"}[1m])",
     "legendFormat": "{{instance}}_PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"$ELK\"}",
     "legendFormat": "{{instance}}_TCP_tw"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~\"$ELK\"}",
     "legendFormat": "{{instance}}_TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~\"$ELK\"}",
     "legendFormat": "{{instance}}_TCP_inuse"
    }
   ]
  }
 ]
}