# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
  - job_name: "grafana"
    static_configs:
    - targets:
      - "127.0.0.1:9100"
      labels:
        instance: 'grafana'
#############ELK###################
  - job_name: "Nginx"
    static_configs:
    - targets:
      - "10.104.0.122:9100"
      labels:
        instance: '10.104.0.122'
#############ELK###################
  - job_name: "ELK"
    static_configs:
    - targets:
      - "10.104.158.1:9100"
      labels:
        instance: 'elk-1'
    - targets:
      - "10.104.133.147:9100"
      labels:
        instance: 'elk2-147'
    - targets:
      - "10.104.159.169:9100"
      labels:
        instance: 'elk3-169'
############教研组############
  - job_name: "JY"
    static_configs:
    - targets:
      - "10.104.25.15:9100"
      labels:
        instance: 'jy-15'
    - targets:
      - "10.104.154.148:9100"
      labels:
        instance: 'jy-148'
###############LP##############
  - job_name: "LP"
    static_configs:
    - targets:
      - "10.104.9.134:9100"
      labels:
        instance: 'LP-134'
    - targets:
      - "10.104.8.210:9100"
      labels:
        instance: 'LP-210'
################# CC##################
  - job_name: "CC"
    static_configs:
    - targets:
      - "10.104.30.21:9100"
      labels:
        instance: 'CC-21'
    - targets:
      - "10.104.153.59:9100"
      labels:
        instance: 'CC-59'
################mysql#############
  - job_name: "mysql"
    scrape_interval: 5s
    static_configs:
    - targets: ['10.104.150.60:9101']
      labels:
        instance: 主库
    - targets: ['10.104.150.60:9102']
      labels:
        instance: cc-业务
    - targets: ['10.104.150.60:9103']
      labels:
        instance: 数据中心
    - targets: ['10.104.150.60:9104']
      labels:
        instance: 登录认证权限专用
    - targets: ['10.104.150.60:9105']
      labels:
        instance: crm-1
    - targets: ['10.104.150.60:9107']
      labels:
        instance: crm-2
    - targets: ['10.104.150.60:9108']
      labels:
        instance: 灾备
    - targets: ['10.104.150.60:9109']
      labels:
        instance: 排课系统
[root@grafana prometheus]# cat prometheus.yml 
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
  - job_name: "grafana"
    static_configs:
    - targets:
      - "127.0.0.1:9100"
      labels:
        instance: 'grafana'
#############ELK###################
  - job_name: "Nginx"
    static_configs:
    - targets:
      - "10.104.0.122:9100"
      labels:
        instance: '10.104.0.122'
#############ELK###################
  - job_name: "ELK"
    static_configs:
    - targets:
      - "10.104.158.1:9100"
      labels:
        instance: 'elk-1'
    - targets:
      - "10.104.133.147:9100"
      labels:
        instance: 'elk2-147'
    - targets:
      - "10.104.159.169:9100"
      labels:
        instance: 'elk3-169'
############教研组############
  - job_name: "JY"
    static_configs:
    - targets:
      - "10.104.25.15:9100"
      labels:
        instance: 'jy-15'
    - targets:
      - "10.104.154.148:9100"
      labels:
        instance: 'jy-148'
###############LP##############
  - job_name: "LP"
    static_configs:
    - targets:
      - "10.104.9.134:9100"
      labels:
        instance: 'LP-134'
    - targets:
      - "10.104.8.210:9100"
      labels:
        instance: 'LP-210'
################# CC##################
  - job_name: "CC"
    static_configs:
    - targets:
      - "10.104.30.21:9100"
      labels:
        instance: 'CC-21'
    - targets:
      - "10.104.153.59:9100"
      labels:
        instance: 'CC-59'
################mysql#############
  - job_name: "mysql"
    scrape_interval: 5s
    static_configs:
    - targets: ['10.104.150.60:9101']
      labels:
        instance: 主库
    - targets: ['10.104.150.60:9102']
      labels:
        instance: cc-业务
    - targets: ['10.104.150.60:9103']
      labels:
        instance: 数据中心
    - targets: ['10.104.150.60:9104']
      labels:
        instance: 登录认证权限专用
    - targets: ['10.104.150.60:9105']
      labels:
        instance: crm-1
    - targets: ['10.104.150.60:9107']
      labels:
        instance: crm-2
    - targets: ['10.104.150.60:9108']
      labels:
        instance: 灾备
    - targets: ['10.104.150.60:9109']
      labels:
        instance: 排课系统